spring:
  cloud:
    gateway:
      routes:
        - id: usermanagementservice
          uri: lb://usermanagementservice
          predicates:
            - Path=/athletes/**,/coaches/**
          filters:
            - AuthenticationFilter

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: eventservice
          uri: lb://eventservice
          predicates:
            - Path=/event/**,/meet/**
          filters:
            - AuthenticationFilter
        - id: wellness
          uri: lb://wellness
          predicates:
            - Path=/wellness/**
          filters:
            - AuthenticationFilter
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://127.0.0.1:3000,http://127.0.0.1:3001"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS

  application:
    name: athlete-gateway

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/