openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8902
    description: Generated server url
paths:
  /wellness/weight-plan:
    post:
      tags:
        - well-ness-controller
      operationId: createOrUpdateWeightPlan
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WeightPlan'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/WeightPlan'
  /wellness/daily-diet:
    post:
      tags:
        - well-ness-controller
      operationId: createOrUpdateDailyDiet
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DailyDiet'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/DailyDiet'
  /wellness/recommendation/{athleteId}:
    get:
      tags:
        - well-ness-controller
      operationId: getAIRecommendedDiet
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
        - name: athleteId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /wellness/daily-diet/{athleteId}:
    get:
      tags:
        - well-ness-controller
      operationId: getDailyDietByAthleteId
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
        - name: athleteId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DailyDiet'
components:
  schemas:
    WeightPlan:
      type: object
      properties:
        id:
          type: integer
          format: int64
        athleteId:
          type: string
        startWeight:
          type: integer
          format: int64
        targetWeight:
          type: integer
          format: int64
        preference:
          type: string
        dailyCalorieGoal:
          type: integer
          format: int64
    DailyDiet:
      type: object
      properties:
        id:
          type: integer
          format: int64
        athleteId:
          type: string
        date:
          type: string
          format: date-time
        calories:
          type: integer
          format: int64
        currentWeight:
          type: integer
          format: int64
        weightPlan:
          $ref: '#/components/schemas/WeightPlan'
