spring:
  application:
    name: auth-service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: ${HOSTNAME}

server:
  port: 9899