spring:
  cloud:
    gateway:
      routes:
        - id: usermanagementservice
          uri: http://localhost:8900
          predicates:
            - Path=/athletes/**,/coaches/**
          filters:
            - AuthenticationFilter

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: eventservice
          uri: http://localhost:8901
          predicates:
            - Path=/event/**,/meet/**
          filters:
            - AuthenticationFilter
        - id: wellness
          uri: http://localhost:8902
          predicates:
            - Path=/wellness/**
          filters:
            - AuthenticationFilter

  application:
    name: athlete-gateway

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/