spring:
  cloud:
    gateway:
      routes:
        - id: usermanagementservice
          uri: http://localhost:8900
          predicates:
            - Path=/athletes/**
          filters:
            - AuthenticationFilter

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

  application:
    name: athlete-gateway

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/